CREATE TABLE bilibili_user_full(
  mid INT NOT NULL ,
  name VARCHAR(30) DEFAULT NULL ,
  sex VARCHAR(2) DEFAULT NULL ,
  level INT DEFAULT 1,
  sign VARCHAR(80) DEFAULT NULL ,
  faceUrl VARCHAR(80) DEFAULT NULL ,
  friends INT DEFAULT NULL ,
  fans INT DEFAULT NULL ,
  playNum INT DEFAULT NULL ,
  birthday DATE DEFAULT NULL ,
  place VARCHAR(8) DEFAULT NULL ,
  PRIMARY KEY (mid)
) ENGINE=innoDB DEFAULT CHARSET=utf8;